



#ifndef _ANTICPSVRFUNC_H
#define _ANTICPSVRFUNC_H

#define ANTICPSVRREQLEN		48
#define ANTICPSVRACKLEN		24	
#define ANTICPSVRVERLEN		36



#define ERROR_ANTICPSVR_BASECODE						0x0001C000
#define ERROR_ANTICPSVR_INIT_INVALIDPARAM				ERROR_ANTICPSVR_BASECODE + 0x1
#define ERROR_ANTICPSVR_INIT_CREATEFILE_FAIL			ERROR_ANTICPSVR_BASECODE + 0x2
#define ERROR_ANTICPSVR_INIT_CREATEFILEMAP_FAIL			ERROR_ANTICPSVR_BASECODE + 0x3
#define ERROR_ANTICPSVR_INIT_MAPVIEWFILE_FAIL			ERROR_ANTICPSVR_BASECODE + 0x4
#define ERROR_ANTICPSVR_INIT_GETFILESIZE_FAIL			ERROR_ANTICPSVR_BASECODE + 0x5
#define ERROR_ANTICPSVR_MAKEFILEHASH_INVALIDPARAM		ERROR_ANTICPSVR_BASECODE + 0x6
#define ERROR_ANTICPSVR_MAKEFILEHASH_CREATEFILE_FAIL	ERROR_ANTICPSVR_BASECODE + 0x7
#define ERROR_ANTICPSVR_MAKEFILEHASH_CREATEFILEMAP_FAIL	ERROR_ANTICPSVR_BASECODE + 0x8
#define ERROR_ANTICPSVR_MAKEFILEHASH_GETFILESIZE_FAIL	ERROR_ANTICPSVR_BASECODE + 0x9
#define ERROR_ANTICPSVR_MAKEFILEHASH_MAPVIEWFILE_FAIL	ERROR_ANTICPSVR_BASECODE + 0xA
#define ERROR_ANTICPSVR_MAKEFILEHASH_GETHASHINFO_FAIL	ERROR_ANTICPSVR_BASECODE + 0xB
#define ERROR_ANTICPSVR_MAKEFILEHASH_WRITEFILE_FAIL		ERROR_ANTICPSVR_BASECODE + 0xC
#define ERROR_ANTICPSVR_MAKEREQMSG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0xD
#define ERROR_ANTICPSVR_MAKEREQMSG_MAKESKEY_FAIL		ERROR_ANTICPSVR_BASECODE + 0xE
#define ERROR_ANTICPSVR_MAKEREQMSG_INITCRYPT_FAIL		ERROR_ANTICPSVR_BASECODE + 0xF
#define ERROR_ANTICPSVR_MAKEREQMSG_ENCCRYPT_FAIL		ERROR_ANTICPSVR_BASECODE + 0x10
#define ERROR_ANTICPSVR_MAKEREQMSG_GETRNDHASHINFO_FAIL	ERROR_ANTICPSVR_BASECODE + 0x11
#define ERROR_ANTICPSVR_MAKEREQMSG_CREUSTRING_FAIL		ERROR_ANTICPSVR_BASECODE + 0x12
#define ERROR_ANTICPSVR_MAKEREQMSG_ENCB64_FAIL			ERROR_ANTICPSVR_BASECODE + 0x13
#define ERROR_ANTICPSVR_MAKEREQMSG_STRCOPY_FAIL			ERROR_ANTICPSVR_BASECODE + 0x14

#define ERROR_ANTICPSVR_GETHASHSECTION_INVALIDPARAM		ERROR_ANTICPSVR_BASECODE + 0x14
#define ERROR_ANTICPSVR_GETHASHSECTION_CREATEFILE_FAIL	ERROR_ANTICPSVR_BASECODE + 0x15
#define ERROR_ANTICPSVR_GETHASHSECTION_GETFILESIZE_FAIL	ERROR_ANTICPSVR_BASECODE + 0x16
#define ERROR_ANTICPSVR_GETHASHSECTION_FILESIZE_SHORT	ERROR_ANTICPSVR_BASECODE + 0x17
#define ERROR_ANTICPSVR_ANALACKMSG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x18
#define ERROR_ANTICPSVR_ANALACKMSG_MAKESKEY_FAIL		ERROR_ANTICPSVR_BASECODE + 0x19
#define ERROR_ANTICPSVR_ANALACKMSG_INITCRYPT_FAIL		ERROR_ANTICPSVR_BASECODE + 0x1A
#define ERROR_ANTICPSVR_ANALACKMSG_DECRYPT_FAIL  		ERROR_ANTICPSVR_BASECODE + 0x1B
#define ERROR_ANTICPSVR_ANALACKMSG_CREATEUSTR_FAIL 		ERROR_ANTICPSVR_BASECODE + 0x1C
#define ERROR_ANTICPSVR_ANALACKMSG_DECB64_FAIL 			ERROR_ANTICPSVR_BASECODE + 0x1D
#define ERROR_ANTICPSVR_ANALACKMSG_COPYPNT_FAIL			ERROR_ANTICPSVR_BASECODE + 0x1E

#define ERROR_ANTICPSVR_MAKEHSFLAG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x30
#define ERROR_ANTICPSVR_INITCRYPT_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x31
#define ERROR_ANTICPSVR_MAKESESSIONKEY_INVALIDPARAM		ERROR_ANTICPSVR_BASECODE + 0x32
#define ERROR_ANTICPSVR_GETENCMSG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x33
#define ERROR_ANTICPSVR_GETDECMSG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x34
#define ERROR_ANTICPSVR_MAKEACKSEQ_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x35
#define ERROR_ANTICPSVR_ISVALIDSEQ_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x36
#define ERROR_ANTICPSVR_GETRNDHASHINFO_INVALIDPARAM		ERROR_ANTICPSVR_BASECODE + 0x37


#define ERROR_ANTICPSVR_ANALACKMSG_HSHIELD_ERROR 		ERROR_ANTICPSVR_BASECODE + 0x40

#define ERROR_ANTICPSVR_ANALACKMSG_PACKET_ERROR 		ERROR_ANTICPSVR_BASECODE + 0x41

#define ERROR_ANTICPSVR_ANALACKMSG_FILE_ERROR			ERROR_ANTICPSVR_BASECODE + 0x42

#define ERROR_ANTICPSVR_ANALCNTMSG_INVALIDPARAM			ERROR_ANTICPSVR_BASECODE + 0x50
#define ERROR_ANTICPSVR_ANALCNTMSG_INITCRYPT_FAIL		ERROR_ANTICPSVR_BASECODE + 0x51
#define ERROR_ANTICPSVR_ANALCNTMSG_DECRYPT_FAIL			ERROR_ANTICPSVR_BASECODE + 0x52


#ifdef ANTICPSVR_EXPORTS
#define ANTICPSVR_API  extern "C" __declspec(dllexport)
#else
#define ANTICPSVR_API  extern "C" __declspec(dllimport)
#endif


ANTICPSVR_API DWORD __stdcall _AntiCpSvr_Initialize( LPCTSTR lpszFilePath,			
													 PBYTE *ppBasePointer,			
													 LPDWORD pdwMemSize );			



ANTICPSVR_API void __stdcall _AntiCpSvr_Finalize( PBYTE pBasePointer );				



ANTICPSVR_API DWORD __stdcall _AntiCpSvr_MakeReqMsg( PBYTE pBasePointer,	    
												     DWORD dwMemSize,			
												     PBYTE pbyReqMsg,			
												     PBYTE pbyReqInfo );		



ANTICPSVR_API DWORD __stdcall _AntiCpSvr_AnalyzeAckMsg( PBYTE pByAckMsg,			
													    PBYTE pBasePointer,			
												        PBYTE pbyReqInfo );			

																		


ANTICPSVR_API DWORD __stdcall _AntiCpSvr_AnalyzeCntMsg( IN PBYTE pbyCntMsg,			
														IN PBYTE pbyVerInfo,		
													    IN PBYTE pBasePointer,		
												        OUT PBOOL pbResult );		
#endif 