



#ifndef _ANTICPCNT_H
#define _ANTICPCNT_H

#if defined(__cplusplus)
extern "C"
{
#endif

#define ANTICPCNTREQLEN		48
#define ANTICPCNTACKLEN		24
#define ANTICPCNTVERLEN		36


#define ERROR_ANTICPCNT_BASECODE						0x0001D000
#define ERROR_ANTICPCNT_INITCRYPT_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x1
#define ERROR_ANTICPCNT_MAKESESSIONKEY_INVALIDPARAM		ERROR_ANTICPCNT_BASECODE + 0x2
#define ERROR_ANTICPCNT_GETENCMSG_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x3
#define ERROR_ANTICPCNT_GETDECMSG_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x4
#define ERROR_ANTICPCNT_GETFILEHASH_INVALIDPARAM		ERROR_ANTICPCNT_BASECODE + 0x5
#define ERROR_ANTICPCNT_GETFILEHASH_CREATEFILE_FAIL		ERROR_ANTICPCNT_BASECODE + 0x6
#define ERROR_ANTICPCNT_GETFILEHASH_CREATEFILEMAP_FAIL	ERROR_ANTICPCNT_BASECODE + 0x7
#define ERROR_ANTICPCNT_GETFILEHASH_GETFILESIZE_FAIL	ERROR_ANTICPCNT_BASECODE + 0x8
#define ERROR_ANTICPCNT_GETFILEHASH_MAPVIEWFILE_FAIL	ERROR_ANTICPCNT_BASECODE + 0x9
#define ERROR_ANTICPCNT_MAKEACKMSG_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0xA
#define ERROR_ANTICPCNT_MAKEACKMSG_MAKESKEY_FAIL		ERROR_ANTICPCNT_BASECODE + 0xB
#define ERROR_ANTICPCNT_MAKEACKMSG_INITCRYPT_FAIL		ERROR_ANTICPCNT_BASECODE + 0xC
#define ERROR_ANTICPCNT_MAKEACKMSG_DECRYPT_FAIL			ERROR_ANTICPCNT_BASECODE + 0xD
#define ERROR_ANTICPCNT_MAKEACKMSG_GETFILEHASH_FAIL		ERROR_ANTICPCNT_BASECODE + 0xE
#define ERROR_ANTICPCNT_MAKEACKMSG_MAKEHSFLAG_FAIL		ERROR_ANTICPCNT_BASECODE + 0xF
#define ERROR_ANTICPCNT_MAKEACKMSG_MAKACKSEQ_FAIL		ERROR_ANTICPCNT_BASECODE + 0x10
#define ERROR_ANTICPCNT_MAKEACKMSG_ENCRYPT_FAIL			ERROR_ANTICPCNT_BASECODE + 0x11
#define ERROR_ANTICPCNT_MAKEACKMSG_COPYPNT_FAIL			ERROR_ANTICPCNT_BASECODE + 0x12
	
#define ERROR_ANTICPCNT_MAKEHSFLAG_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x13
#define ERROR_ANTICPCNT_MAKEACKSEQ_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x14
#define ERROR_ANTICPCNT_MAKEACKMSG_GETMODNAME_FAIL		ERROR_ANTICPCNT_BASECODE + 0x15
#define ERROR_ANTICPCNT_MAKEACKMSG_CREATEUSTR_FAIL		ERROR_ANTICPCNT_BASECODE + 0x16
	
#define ERROR_ANTICPCNT_MAKECNTMSG_INVALIDPARAM			ERROR_ANTICPCNT_BASECODE + 0x20
#define ERROR_ANTICPCNT_MAKECNTMSG_GETMODNAME_FAIL		ERROR_ANTICPCNT_BASECODE + 0x21
#define ERROR_ANTICPCNT_MAKECNTMSG_CREATEFILE_FAIL		ERROR_ANTICPCNT_BASECODE + 0x22
#define ERROR_ANTICPCNT_MAKECNTMSG_GETFILESIZE_FAIL		ERROR_ANTICPCNT_BASECODE + 0x23
#define ERROR_ANTICPCNT_MAKECNTMSG_GETFILEHASH_FAIL		ERROR_ANTICPCNT_BASECODE + 0x24
#define ERROR_ANTICPCNT_MAKECNTMSG_INITCRYPT_FAIL		ERROR_ANTICPCNT_BASECODE + 0x25
#define ERROR_ANTICPCNT_MAKECNTMSG_ENCRYPT_FAIL			ERROR_ANTICPCNT_BASECODE + 0x26
	

DWORD __stdcall _AntiCpCnt_MakeAckMsg( PBYTE pbyReqMsg,			
									   PBYTE pbyAckMsg );		



DWORD __stdcall _AntiCpCnt_MakeCntMsg( IN PBYTE pbyInput,				
									   OUT PBYTE pbyOutput,				
									   IN int nOutputLen );				
									   
#if defined(__cplusplus)
}
#endif 

#endif 
