

#define GAME_PROTOCOL_VERSION	"GTH_GPV_20030410"



#define CC_CONNECT_MASTERSERVER				0x01
#define CC_DISCONNECT_MASTERSERVER			0x02
#define CC_REQUEST_LOGIN					0x03
#define CC_REQUEST_NOTICE					0x04
#define CC_REQUEST_SERVERGROUP				0x05
#define CC_REQUEST_GAMEDATA					0x06
#define CC_REQUEST_GAMESERVERADDR			0x07

#define CC_REQUEST_READYCREATE				0x08
#define CC_REQUEST_CREATECHARACTER			0x09
#define CC_REQUEST_DELETECHARACTER			0x0a
#define CC_REQUEST_CHECKCHARNAME			0x0b


#define CC_REQUEST_LOADCHARACTER_SLOT		0x0c
#define CC_REQUEST_SAVECHARACTER_SLOT		0x0d



#define CC_CONNECT_GAMESERVER				0x10							
#define CC_DISCONNECT_GAMESERVER			0x11
#define CC_READYTOPLAY						0x12
#define CC_SYNCMESSAGE						0x13
#define CC_CHATMESSAGE						0x14
#define CC_CHATMESSAGE_WHISPER				0x15
#define CC_CHATMESSAGE_PARTY				0x16
#define CC_CHATMESSAGE_DAN					0x17
#define CC_TRANSPORTWORLD					0x18
#define CC_CALLGAMEMASTER					0x19
#define CC_REQUESTSUMMONS					0x1a
#define CC_REPLYSUMMONS						0x1b
#define CC_UPDATEPOSITION					0x1c
#define CC_EVENT_IDLE						0x1d	
#define CC_EVENT_WALK						0x1e	
#define CC_EVENT_WALKLEFT					0x1f	

#define CC_EVENT_WALKRIGHT					0x20	
#define CC_EVENT_BACK						0x21	
#define CC_EVENT_BACKLEFT					0x22	
#define CC_EVENT_BACKRIGHT					0x23	
#define CC_EVENT_RUN						0x24	
#define CC_EVENT_RUNLEFT					0x25	
#define CC_EVENT_RUNRIGHT					0x26	
#define CC_EVENT_TURNLEFT					0x27	
#define CC_EVENT_TURNRIGHT					0x28	
#define CC_EVENT_MOVELEFT					0x29	
#define CC_EVENT_MOVERIGHT					0x2a	
#define CC_EVENT_ATTACK						0x2b	
#define CC_EVENT_RESPAWN					0x2c	
#define CC_EVENT_MOUSEWALK					0x2d	
#define CC_EVENT_MOUSERUN					0x2e	
#define CC_EVENT_SIT						0x2f

#define CC_EVENT_STAND						0x30	
#define CC_EVENT_SKILL						0x31	
#define CC_DROPITEM							0x32
#define CC_PICKUPITEM						0x33
#define CC_REQUEST_GETINVENTORYITEM			0x34
#define CC_REQUEST_GETEQUIPITEM				0x35
#define	CC_REQUEST_ENTITYMENU				0x36
#define CC_REQUEST_NPCCHAT					0x37
#define CC_REQUEST_QUITNPCCHAT				0x38
#define CC_REQUEST_NPCSELECTMESSAGE			0x39
#define CC_REQUEST_WEAPONCHANGE				0x3a
#define CC_REQUEST_GENCHANGE				0x3b
#define	CC_REQUEST_STATUSUP					0x3c
#define	CC_REQUEST_STORE					0x3d
#define CC_REQUEST_BUYITEM					0x3e
#define CC_REQUEST_SELLITEM					0x3f

#define CC_REQUEST_DEBUGLEVELUP				0x40
#define	CC_REQUEST_BINDING					0x41
#define	CC_REQUEST_EPACKSTORE				0x42
#define	CC_REQUEST_EPACKUSE					0x43
#define CC_REQUEST_REPAIR					0x44
#define CC_REQUEST_DESTORY_ITEM				0x45


#define CC_REQUEST_PCTRADE					0x46




#define GSC_SERVERGROUPINFO					0x70
#define GSC_DROPSERVERGROUP					0x71

#define GSC_MEMBERSERVERINFO				0x72
#define GSC_MYSERVERINFO					0x73
#define GSC_DROPMYSERVER					0x74



#define GSC_CONNECTREP						0x80
#define GSC_SYNCMESSAGE						0x81	
#define GSC_CHATMESSAGE						0x82
#define GSC_CHATMESSAGE_WHISPER				0x83
#define GSC_CHATMESSAGE_PARTY				0x84
#define GSC_CHATMESSAGE_DAN					0x85
#define GSC_TRANSPORTWORLDREP				0x86
#define GSC_CHANGESERVER					0x87
#define GSC_CHANGEWORLD						0x88
#define GSC_SETSHUTDOWNTIMER				0x89
#define GSC_NOTICEMESSAGE					0x8a
#define GSC_CALLGAMEMASTER					0x8b
#define GSC_REQUESTSUMMONS					0x8c
#define GSC_REPLYSUMMONS					0x8d
#define GSC_EVENT_IDLE						0x8e	
#define GSC_EVENT_WALK						0x8f
	
#define GSC_EVENT_WALKLEFT					0x90	
#define GSC_EVENT_WALKRIGHT					0x91	
#define GSC_EVENT_BACK						0x92	
#define GSC_EVENT_BACKLEFT					0x93	
#define GSC_EVENT_BACKRIGHT					0x94	
#define GSC_EVENT_RUN						0x95	
#define GSC_EVENT_RUNLEFT					0x96	
#define GSC_EVENT_RUNRIGHT					0x97	
#define GSC_EVENT_TURNLEFT					0x98	
#define GSC_EVENT_TURNRIGHT					0x99	
#define GSC_EVENT_MOVELEFT					0x9a	
#define GSC_EVENT_MOVERIGHT					0x9b	
#define GSC_EVENT_ATTACK					0x9c	
#define GSC_EVENT_DAMAGE					0x9d	
#define GSC_EVENT_DIE						0x9e	
#define GSC_EVENT_RESPAWN					0x9f
	
#define GSC_EVENT_MOUSEWALK					0xa0	
#define GSC_EVENT_MOUSERUN					0xa1
#define GSC_EVENT_SIT						0xa2
#define GSC_EVENT_STAND						0xa3
#define GSC_EVENT_SKILL						0xa4
#define GSC_ADDITEMOBJECT					0xa5
#define GSC_SYNCITEMOBJECT					0xa6
#define GSC_DELETEITEMOBJECT				0xa7
#define GSC_REPLY_GETINVENTORYITEM			0xa8
#define GSC_REPLY_GETEQUIPITEM				0xa9
#define GSC_REPLY_DROPITEM					0xaa
#define GSC_REPLY_PICKUPITEM				0xab
#define GSC_ADDMULTIITEMOBJECT				0xac
#define GSC_LOOTVALUE						0xad
#define GSC_REPLY_ENTITYMENU				0xae
#define GSC_REPLY_NPCCHAT					0xaf

#define GSC_REPLY_QUITNPCCHAT				0xb0
#define GSC_NPCMESSAGE						0xb1
#define GSC_REPLY_WEAPONCHANGE				0xb2
#define GSC_LEVELUP							0xb3
#define GSC_REPLY_GENCHANGE					0xb4
#define GSC_REPLY_STATUSUP					0xb5
#define GSC_REPLY_STORE						0xb6
#define GSC_REPLY_BUYITEM					0xb7
#define GSC_REPLY_SELLITEM					0xb8
#define	GSC_REPLY_BINDING					0xb9
#define	GSC_REPLY_EPACKSTORE				0xba
#define	GSC_AUTORECOVERY					0xbb
#define	GSC_REPLY_EPACKUSE					0xbc
#define GSC_REPLY_REPAIR					0xbd
#define GSC_REPLY_DESTORY_ITEM				0xbe


#define GSC_REPLY_PCTRADE					0xbf


#define GSC_SERVERACKMSG					0xc0
#define GSC_NOTFOUNDPC						0xc1



#define MSC_ACCEPTCLIENT					0xe0
#define MSC_PATCHSERVERADDR					0xe1
#define MSC_NOTICEINFO						0xe2	
#define MSC_REPLYLOGIN						0xe3	
#define MSC_SERVERGROUPINFO					0xe4
#define MSC_GAMEDATA						0xe5
#define MSC_GAMESERVERADDR					0xe6
#define MSC_REPLY_READYCREATE				0xe7
#define MSC_REPLY_CREATECHARACTER			0xe8
#define MSC_REPLY_DELETECHARACTER			0xe9
#define MSC_REPLY_CHECKCHARNAME				0xea
#define MSC_REJECTCLIENT					0xeb


#define MSC_LOAD_CHARACTER_SLOT				0xef




#define CC_SYSTEMADMIN						0xf0
#define GSC_SYSTEMADMIN						0xf1

#define GC_RELIABLE_PING					0xf2
#define GC_UNRELIABLE_PING					0xf3


#define CC_MONITOR							0xf4
#define MSC_MONITOR							0xf5




enum
{
	SYSTEMADMIN_SERVERSHUTDOWN		=	0,
	SYSTEMADMIN_SETSHUTDOWNTIMER,
	SYSTEMSDMIN_GOTOPLAYER,
	SYSTEMSDMIN_NOTICE,
	SYSTEMADMIN_SETNOTICEINFO,
	SYSTEMADMIN_REQUESTFINDPC,
	SYSTEMADMIN_REPLYFINDPC,
	SYSTEMSDMIN_GOTOMONSTER,
	SYSTEMSDMIN_GMBUSYONOFF,
	SYSTEMSDMIN_GMHIDEONOFF,
	SYSTEMSDMIN_REQUESTSUMMONMONSTER,
	SYSTEMADMIN_REPLYSUMMONMONSTER,
};



enum
{
	PCTRADE_REQUEST				=	0,
	PCTRADE_ADMIT,
	PCTRADE_REJECT,
	PCTRADE_OK,
	PCTRADE_CANCEL,
	PCTRADE_CONFIRM,
	PCTRADE_EXIT,
	PCTRADE_ITEM,
	PCTRADE_SE,
};



enum
{
	MONITOR_REQUEST_SERVERINFO,		
	MONITOR_REPLY_SERVERINFO,		
	MONITOR_REQUEST_FILTERING,		
	MONITOR_CHANGE_FILLTERING_MESSAGE, 
};
