#define GTH_SOUND_ID_ATTACK_1     0
#define GTH_SOUND_ID_ATTACK_2     1
#define GTH_SOUND_ID_MAGIC_1      2
#define GTH_SOUND_ID_MAGIC_2      3
#define GTH_SOUND_ID_DEAD_1       4
#define GTH_SOUND_ID_DEAD_2       5
#define GTH_SOUND_ID_LEVELUP_1    6
#define GTH_SOUND_ID_HEALING_1   7
#define GTH_SOUND_ID_INTERFACE_SELECT_1     8
#define GTH_SOUND_ID_INTERFACE_SELECT_2     9
#define GTH_SOUND_ID_INTERFACE_MOVE_1       10
#define GTH_SOUND_ID_INTERFACE_MOVE_2       11
#define GTH_SOUND_ID_INTERFACE_TRADE_1      12
#define GTH_SOUND_ID_INTERFACE_TRADE_2      13


static char *g_soundIDString[] = 
{
	
	"GTH_SOUND_ID_BUTTON_CLICK_1",
	"GTH_SOUND_ID_BUTTON_CLICK_2",
	"GTH_SOUND_ID_GEN_CLICK",
	"GTH_SOUND_ID_CHAR_CLICK",
	"GTH_SOUND_ID_OPEN_WINDOW",
	"GTH_SOUND_ID_CLOSE_WINDOW",
	"GTH_SOUND_ID_LOGIN_WINDOW",
	"GTH_SOUND_ID_LOGIN_WINDOW_2",
	"GTH_SOUND_ID_ITEM_CLICK_1",
	"GTH_SOUND_ID_ITEM_CLICK_2",
	"GTH_SOUND_ID_DROP_ITEM",
	"GTH_SOUND_ID_PICKUP_ITEM",
	"GTH_SOUND_ID_EQUIP_ITEM",
	"GTH_SOUND_ID_WARNING_1",
	"GTH_SOUND_ID_WARNING_2",
	"GTH_SOUND_ID_NOTICE",
	"GTH_SOUND_ID_DISAPPEAR_MON",
	
	"GTH_SOUND_ID_REPAIRWARNING",
	"GTH_SOUND_ID_LOGIN_WINDOW3",
	"GTH_SOUND_ID_LOGIN_BUTTONSHOW",
	"GTH_SOUND_ID_LOGIN_ITEMABSORB",


	
	"GTH_SOUND_ID_GAMELOGIN_OK",
	"GTH_SOUND_ID_REPAIR",
	"GTH_SOUND_ID_SPAWNFIELD_MON",
	"GTH_SOUND_ID_SPAWNDUN_MON",
	"GTH_SOUND_ID_SPAWN_ITEM",

	"GTH_SOUND_ID_PC_HEARTBEAT_0",
	"GTH_SOUND_ID_PC_HEARTBEAT_1",
	"GTH_SOUND_ID_PC_HEARTBEAT_2",
	"GTH_SOUND_ID_PC_RECOVERY_RA",
	"GTH_SOUND_ID_PC_RECOVERY_SA",

	"GTH_SOUND_ID_DISAPPEAR_MON2",
	"GTH_SOUND_ID_LEVELUP",
	"GTH_SOUND_ID_CHARSPAWN",

	
	"GTH_SOUND_ID_QUESTSCROLL_DROP",
	"GTH_SOUND_ID_QUESTSCROLL_WRITING",
	
	"GTH_SOUND_ID_BATTLE_COUNT",	
	"GTH_SOUND_ID_CONG",			
	"GTH_SOUND_ID_BATTLE_FAIL",	
	"GTH_SOUND_ID_BATTLE_FIGHT",	
	"GTH_SOUND_ID_BATTLE_READY",	
	"GTH_SOUND_ID_BATTLE_SUCCESS",
	"GTH_SOUND_ID_BATTLE_READYFIGHT",
	


	
	"GTH_SOUND_ID_WEAPON_0",
	"GTH_SOUND_ID_WEAPON_1",
	"GTH_SOUND_ID_WEAPON_2",
	"GTH_SOUND_ID_WEAPON_3",
	
	"GTH_SOUND_ID_WEAPON_4",
	"GTH_SOUND_ID_WEAPON_5",
	"GTH_SOUND_ID_WEAPON_6",
	
	"GTH_SOUND_ID_WEAPON_7",
	"GTH_SOUND_ID_WEAPON_8",
	"GTH_SOUND_ID_WEAPON_9",



	
	"GTH_SOUND_ID_MONSTER_IDLE_0",
	"GTH_SOUND_ID_MONSTER_IDLE_1",
	"GTH_SOUND_ID_MONSTER_IDLE_2",
	"GTH_SOUND_ID_MONSTER_IDLE_3",
	"GTH_SOUND_ID_MONSTER_IDLE_4",
	"GTH_SOUND_ID_MONSTER_IDLE_5",
	"GTH_SOUND_ID_MONSTER_IDLE_6",
	"GTH_SOUND_ID_MONSTER_IDLE_7",
	"GTH_SOUND_ID_MONSTER_IDLE_8",
	
	"GTH_SOUND_ID_MONSTER_IDLE_9",
	"GTH_SOUND_ID_MONSTER_IDLE_10",
	"GTH_SOUND_ID_MONSTER_IDLE_11",


	"GTH_SOUND_ID_MONSTER_DAMAGE_0",
	"GTH_SOUND_ID_MONSTER_DAMAGE_1",
	"GTH_SOUND_ID_MONSTER_DAMAGE_2",
	"GTH_SOUND_ID_MONSTER_DAMAGE_3",
	"GTH_SOUND_ID_MONSTER_DAMAGE_4",
	"GTH_SOUND_ID_MONSTER_DAMAGE_5",
	"GTH_SOUND_ID_MONSTER_DAMAGE_6",
	"GTH_SOUND_ID_MONSTER_DAMAGE_7",
	
	"GTH_SOUND_ID_MONSTER_DAMAGE_8",
	"GTH_SOUND_ID_MONSTER_DAMAGE_9",
	"GTH_SOUND_ID_MONSTER_DAMAGE_10",


	"GTH_SOUND_ID_MONSTER_DIE_0",
	"GTH_SOUND_ID_MONSTER_DIE_1",
	"GTH_SOUND_ID_MONSTER_DIE_2",
	"GTH_SOUND_ID_MONSTER_DIE_3",
	"GTH_SOUND_ID_MONSTER_DIE_4",
	"GTH_SOUND_ID_MONSTER_DIE_5",
	"GTH_SOUND_ID_MONSTER_DIE_6",
	"GTH_SOUND_ID_MONSTER_DIE_7",
	"GTH_SOUND_ID_MONSTER_DIE_8",
	"GTH_SOUND_ID_MONSTER_DIE_9",
	"GTH_SOUND_ID_MONSTER_DIE_10",
	"GTH_SOUND_ID_MONSTER_DIE_11",
	"GTH_SOUND_ID_MONSTER_DIE_12",
	"GTH_SOUND_ID_MONSTER_DIE_13",
	"GTH_SOUND_ID_MONSTER_DIE_14",
	
	"GTH_SOUND_ID_MONSTER_DIE_15",
	
	"GTH_SOUND_ID_MONSTER_DIE_16",
	"GTH_SOUND_ID_MONSTER_DIE_17",
	"GTH_SOUND_ID_MONSTER_DIE_18",
	"GTH_SOUND_ID_MONSTER_DIE_19",
	"GTH_SOUND_ID_MONSTER_DIE_20",
	"GTH_SOUND_ID_MONSTER_DIE_21",
	"GTH_SOUND_ID_MONSTER_DIE_22",
	"GTH_SOUND_ID_MONSTER_DIE_23",
	"GTH_SOUND_ID_MONSTER_DIE_24",


	"GTH_SOUND_ID_MONSTER_SHOCK_0",
	"GTH_SOUND_ID_MONSTER_SHOCK_1",
	"GTH_SOUND_ID_MONSTER_SHOCK_2",
	"GTH_SOUND_ID_MONSTER_SHOCK_3",
	"GTH_SOUND_ID_MONSTER_SHOCK_4",
	"GTH_SOUND_ID_MONSTER_SHOCK_5",
	"GTH_SOUND_ID_MONSTER_SHOCK_6",
	"GTH_SOUND_ID_MONSTER_SHOCK_7",
	"GTH_SOUND_ID_MONSTER_SHOCK_8",
	"GTH_SOUND_ID_MONSTER_SHOCK_9",
	"GTH_SOUND_ID_MONSTER_SHOCK_10",
	
	"GTH_SOUND_ID_MONSTER_SHOCK_11",
	
	"GTH_SOUND_ID_MONSTER_SHOCK_12",
	"GTH_SOUND_ID_MONSTER_SHOCK_13",
	"GTH_SOUND_ID_MONSTER_SHOCK_14",
	"GTH_SOUND_ID_MONSTER_SHOCK_15",
	"GTH_SOUND_ID_MONSTER_SHOCK_16",
	"GTH_SOUND_ID_MONSTER_SHOCK_17",
	"GTH_SOUND_ID_MONSTER_SHOCK_18",
	"GTH_SOUND_ID_MONSTER_SHOCK_19",
	"GTH_SOUND_ID_MONSTER_SHOCK_20",

	"GTH_SOUND_ID_MONSTER_MOVE_0",
	"GTH_SOUND_ID_MONSTER_MOVE_1",
	"GTH_SOUND_ID_MONSTER_MOVE_2",
	
	"GTH_SOUND_ID_MONSTER_MOVE_3",
	
	"GTH_SOUND_ID_MONSTER_MOVE_4",
	"GTH_SOUND_ID_MONSTER_MOVE_5",
	"GTH_SOUND_ID_MONSTER_MOVE_6",
	"GTH_SOUND_ID_MONSTER_MOVE_7",
	"GTH_SOUND_ID_MONSTER_MOVE_8",
	"GTH_SOUND_ID_MONSTER_MOVE_9",
	"GTH_SOUND_ID_MONSTER_MOVE_10",
	"GTH_SOUND_ID_MONSTER_MOVE_11",


	"GTH_SOUND_ID_MONSTER_ATTACK_0",
	"GTH_SOUND_ID_MONSTER_ATTACK_1",
	"GTH_SOUND_ID_MONSTER_ATTACK_2",
	"GTH_SOUND_ID_MONSTER_ATTACK_3",
	"GTH_SOUND_ID_MONSTER_ATTACK_4",	
	"GTH_SOUND_ID_MONSTER_ATTACK_5",
	"GTH_SOUND_ID_MONSTER_ATTACK_6",
	"GTH_SOUND_ID_MONSTER_ATTACK_7",
	"GTH_SOUND_ID_MONSTER_ATTACK_8",
	
	"GTH_SOUND_ID_MONSTER_ATTACK_9",
	
	"GTH_SOUND_ID_MONSTER_ATTACK_10",
	"GTH_SOUND_ID_MONSTER_ATTACK_11",
	"GTH_SOUND_ID_MONSTER_ATTACK_12",
	"GTH_SOUND_ID_MONSTER_ATTACK_13",
	"GTH_SOUND_ID_MONSTER_ATTACK_14",
	"GTH_SOUND_ID_MONSTER_ATTACK_15",
	"GTH_SOUND_ID_MONSTER_ATTACK_16",
	"GTH_SOUND_ID_MONSTER_ATTACK_17",

	
	"GTH_SOUND_ID_PC_WALK_0",
	"GTH_SOUND_ID_PC_WALK_1",
	"GTH_SOUND_ID_PC_WALK_2",
	"GTH_SOUND_ID_PC_WALK_3",	
	"GTH_SOUND_ID_PC_WALK_4",
	"GTH_SOUND_ID_PC_WALK_5",
	
	"GTH_SOUND_ID_PC_WALK_6",
	"GTH_SOUND_ID_PC_WALK_7",
	"GTH_SOUND_ID_PC_WALK_8",
	"GTH_SOUND_ID_PC_WALK_9",


	"GTH_SOUND_ID_PC_RUN_0",
	"GTH_SOUND_ID_PC_RUN_1",	
	"GTH_SOUND_ID_PC_RUN_2",	
	"GTH_SOUND_ID_PC_RUN_3",	
	"GTH_SOUND_ID_PC_RUN_4",	
	"GTH_SOUND_ID_PC_RUN_5",
	
	"GTH_SOUND_ID_PC_RUN_6",	
	"GTH_SOUND_ID_PC_RUN_7",	
	"GTH_SOUND_ID_PC_RUN_8",	
	"GTH_SOUND_ID_PC_RUN_9",


	"GTH_SOUND_ID_PC_DIE_0",
	"GTH_SOUND_ID_PC_DIE_1",
	"GTH_SOUND_ID_PC_DIE_2",
	"GTH_SOUND_ID_PC_DIE_3",

	"GTH_SOUND_ID_PC_SHOCK_0",
	"GTH_SOUND_ID_PC_SHOCK_1",
	"GTH_SOUND_ID_PC_SHOCK_2",
	"GTH_SOUND_ID_PC_SHOCK_3",

	"GTH_SOUND_ID_PC_LEVELUP_0",

	"GTH_SOUND_ID_PC_CHARSPAWN_0",

		
	"GTH_SOUND_ID_ENTITY_TEST",


};

typedef enum
{
	GTH_SOUND_ID_BUTTON_CLICK_1			=	0,
	GTH_SOUND_ID_BUTTON_CLICK_2,
	GTH_SOUND_ID_GEN_CLICK,
	GTH_SOUND_ID_CHAR_CLICK,
	GTH_SOUND_ID_OPEN_WINDOW,
	GTH_SOUND_ID_CLOSE_WINDOW,
	GTH_SOUND_ID_LOGIN_WINDOW,
	GTH_SOUND_ID_LOGIN_WINDOW_2,
	GTH_SOUND_ID_ITEM_CLICK_1,
	GTH_SOUND_ID_ITEM_CLICK_2,
	GTH_SOUND_ID_DROP_ITEM,
	GTH_SOUND_ID_PICKUP_ITEM,
	GTH_SOUND_ID_EQUIP_ITEM,
	GTH_SOUND_ID_WARNING_1,
	GTH_SOUND_ID_WARNING_2,
	GTH_SOUND_ID_NOTICE,
	GTH_SOUND_ID_DISAPPEAR_MON,
	
	GTH_SOUND_ID_REPAIRWARNING,
	GTH_SOUND_ID_LOGIN_WINDOW3,
	GTH_SOUND_ID_LOGIN_BUTTONSHOW,
	GTH_SOUND_ID_LOGIN_ITEMABSORB,

	GTH_SOUND_ID_GAMELOGIN_OK,
	GTH_SOUND_ID_REPAIR,
	GTH_SOUND_ID_SPAWNFIELD_MON,
	GTH_SOUND_ID_SPAWNDUN_MON,
	GTH_SOUND_ID_SPAWN_ITEM,


	GTH_SOUND_ID_PC_HEARTBEAT_0,
	GTH_SOUND_ID_PC_HEARTBEAT_1,
	GTH_SOUND_ID_PC_HEARTBEAT_2,
	GTH_SOUND_ID_PC_RECOVERY_RA,
	GTH_SOUND_ID_PC_RECOVERY_SA,

	GTH_SOUND_ID_DISAPPEAR_MON2,
	GTH_SOUND_ID_LEVELUP,
	GTH_SOUND_ID_CHARSPAWN,

	
	GTH_SOUND_ID_QUESTSCROLL_DROP,
	GTH_SOUND_ID_QUESTSCROLL_WRITING,

	
	GTH_SOUND_ID_WEAPON_0,
	GTH_SOUND_ID_WEAPON_1,
	GTH_SOUND_ID_WEAPON_2,
	GTH_SOUND_ID_WEAPON_3,
	
	GTH_SOUND_ID_WEAPON_4,
	GTH_SOUND_ID_WEAPON_5,
	GTH_SOUND_ID_WEAPON_6,
	
	GTH_SOUND_ID_WEAPON_7,
	GTH_SOUND_ID_WEAPON_8,
	GTH_SOUND_ID_WEAPON_9,


	
	GTH_SOUND_ID_MONSTER_IDLE_0,
	GTH_SOUND_ID_MONSTER_IDLE_1,
	GTH_SOUND_ID_MONSTER_IDLE_2,
	GTH_SOUND_ID_MONSTER_IDLE_3,
	GTH_SOUND_ID_MONSTER_IDLE_4,
	GTH_SOUND_ID_MONSTER_IDLE_5,
	GTH_SOUND_ID_MONSTER_IDLE_6,
	GTH_SOUND_ID_MONSTER_IDLE_7,
	GTH_SOUND_ID_MONSTER_IDLE_8,
	GTH_SOUND_ID_MONSTER_IDLE_9,
	GTH_SOUND_ID_MONSTER_IDLE_10,
	GTH_SOUND_ID_MONSTER_IDLE_11,

	GTH_SOUND_ID_MONSTER_DAMAGE_0,
	GTH_SOUND_ID_MONSTER_DAMAGE_1,
	GTH_SOUND_ID_MONSTER_DAMAGE_2,
	GTH_SOUND_ID_MONSTER_DAMAGE_3,
	GTH_SOUND_ID_MONSTER_DAMAGE_4,
	GTH_SOUND_ID_MONSTER_DAMAGE_5,
	GTH_SOUND_ID_MONSTER_DAMAGE_6,
	GTH_SOUND_ID_MONSTER_DAMAGE_7,
	GTH_SOUND_ID_MONSTER_DAMAGE_8,
	GTH_SOUND_ID_MONSTER_DAMAGE_9,
	GTH_SOUND_ID_MONSTER_DAMAGE_10,

	GTH_SOUND_ID_MONSTER_DIE_0,
	GTH_SOUND_ID_MONSTER_DIE_1,
	GTH_SOUND_ID_MONSTER_DIE_2,
	GTH_SOUND_ID_MONSTER_DIE_3,
	GTH_SOUND_ID_MONSTER_DIE_4,
	GTH_SOUND_ID_MONSTER_DIE_5,
	GTH_SOUND_ID_MONSTER_DIE_6,
	GTH_SOUND_ID_MONSTER_DIE_7,
	GTH_SOUND_ID_MONSTER_DIE_8,
	GTH_SOUND_ID_MONSTER_DIE_9,
	GTH_SOUND_ID_MONSTER_DIE_10,
	GTH_SOUND_ID_MONSTER_DIE_11,
	GTH_SOUND_ID_MONSTER_DIE_12,
	GTH_SOUND_ID_MONSTER_DIE_13,
	GTH_SOUND_ID_MONSTER_DIE_14,

	
	GTH_SOUND_ID_MONSTER_DIE_15,
	
	GTH_SOUND_ID_MONSTER_DIE_16,
	GTH_SOUND_ID_MONSTER_DIE_17,
	GTH_SOUND_ID_MONSTER_DIE_18,
	GTH_SOUND_ID_MONSTER_DIE_19,
	GTH_SOUND_ID_MONSTER_DIE_20,
	GTH_SOUND_ID_MONSTER_DIE_21,
	GTH_SOUND_ID_MONSTER_DIE_22,
	GTH_SOUND_ID_MONSTER_DIE_23,
	GTH_SOUND_ID_MONSTER_DIE_24,


	GTH_SOUND_ID_MONSTER_SHOCK_0,
	GTH_SOUND_ID_MONSTER_SHOCK_1,
	GTH_SOUND_ID_MONSTER_SHOCK_2,
	GTH_SOUND_ID_MONSTER_SHOCK_3,
	GTH_SOUND_ID_MONSTER_SHOCK_4,
	GTH_SOUND_ID_MONSTER_SHOCK_5,
	GTH_SOUND_ID_MONSTER_SHOCK_6,
	GTH_SOUND_ID_MONSTER_SHOCK_7,
	GTH_SOUND_ID_MONSTER_SHOCK_8,
	GTH_SOUND_ID_MONSTER_SHOCK_9,
	GTH_SOUND_ID_MONSTER_SHOCK_10,
	
	GTH_SOUND_ID_MONSTER_SHOCK_11,

	GTH_SOUND_ID_MONSTER_SHOCK_12,
	GTH_SOUND_ID_MONSTER_SHOCK_13,
	GTH_SOUND_ID_MONSTER_SHOCK_14,
	GTH_SOUND_ID_MONSTER_SHOCK_15,
	GTH_SOUND_ID_MONSTER_SHOCK_16,
	GTH_SOUND_ID_MONSTER_SHOCK_17,
	GTH_SOUND_ID_MONSTER_SHOCK_18,
	GTH_SOUND_ID_MONSTER_SHOCK_19,
	GTH_SOUND_ID_MONSTER_SHOCK_20,


	GTH_SOUND_ID_MONSTER_MOVE_0,
	GTH_SOUND_ID_MONSTER_MOVE_1,
	GTH_SOUND_ID_MONSTER_MOVE_2,
	
	GTH_SOUND_ID_MONSTER_MOVE_3,

	GTH_SOUND_ID_MONSTER_MOVE_4,
	GTH_SOUND_ID_MONSTER_MOVE_5,
	GTH_SOUND_ID_MONSTER_MOVE_6,
	GTH_SOUND_ID_MONSTER_MOVE_7,
	GTH_SOUND_ID_MONSTER_MOVE_8,
	GTH_SOUND_ID_MONSTER_MOVE_9,
	GTH_SOUND_ID_MONSTER_MOVE_10,
	GTH_SOUND_ID_MONSTER_MOVE_11,

	GTH_SOUND_ID_MONSTER_ATTACK_0,
	GTH_SOUND_ID_MONSTER_ATTACK_1,
	GTH_SOUND_ID_MONSTER_ATTACK_2,
	GTH_SOUND_ID_MONSTER_ATTACK_3,
	GTH_SOUND_ID_MONSTER_ATTACK_4,	
	GTH_SOUND_ID_MONSTER_ATTACK_5,
	GTH_SOUND_ID_MONSTER_ATTACK_6,
	GTH_SOUND_ID_MONSTER_ATTACK_7,
	GTH_SOUND_ID_MONSTER_ATTACK_8,
	
	GTH_SOUND_ID_MONSTER_ATTACK_9,

	GTH_SOUND_ID_MONSTER_ATTACK_10,
	GTH_SOUND_ID_MONSTER_ATTACK_11,
	GTH_SOUND_ID_MONSTER_ATTACK_12,
	GTH_SOUND_ID_MONSTER_ATTACK_13,
	GTH_SOUND_ID_MONSTER_ATTACK_14,
	GTH_SOUND_ID_MONSTER_ATTACK_15,
	GTH_SOUND_ID_MONSTER_ATTACK_16,
	GTH_SOUND_ID_MONSTER_ATTACK_17,

	
	GTH_SOUND_ID_PC_WALK_0,
	GTH_SOUND_ID_PC_WALK_1,
	GTH_SOUND_ID_PC_WALK_2,
	GTH_SOUND_ID_PC_WALK_3,	
	GTH_SOUND_ID_PC_WALK_4,
	GTH_SOUND_ID_PC_WALK_5,	
	
	GTH_SOUND_ID_PC_WALK_6,
	GTH_SOUND_ID_PC_WALK_7,
	GTH_SOUND_ID_PC_WALK_8,
	GTH_SOUND_ID_PC_WALK_9,

	GTH_SOUND_ID_PC_RUN_0,
	GTH_SOUND_ID_PC_RUN_1,	
	GTH_SOUND_ID_PC_RUN_2,	
	GTH_SOUND_ID_PC_RUN_3,	
	GTH_SOUND_ID_PC_RUN_4,	
	GTH_SOUND_ID_PC_RUN_5,
	
	GTH_SOUND_ID_PC_RUN_6,	
	GTH_SOUND_ID_PC_RUN_7,	
	GTH_SOUND_ID_PC_RUN_8,	
	GTH_SOUND_ID_PC_RUN_9,

	GTH_SOUND_ID_PC_DIE_0,
	GTH_SOUND_ID_PC_DIE_1,
	
	GTH_SOUND_ID_PC_DIE_2,
	GTH_SOUND_ID_PC_DIE_3,

	GTH_SOUND_ID_PC_SHOCK_0,
	GTH_SOUND_ID_PC_SHOCK_1,
	
	GTH_SOUND_ID_PC_SHOCK_2,
	GTH_SOUND_ID_PC_SHOCK_3,

	GTH_SOUND_ID_PC_LEVELUP_0,

	GTH_SOUND_ID_PC_CHARSPAWN_0,

		
	GTH_SOUND_ID_ENTITY_TEST,

	NUM_GTH_SOUND_ID

} GTH_SOUND_ID_t;

