enum
{
	ERROR_BUYITEM_NONE		= 0,	
	ERROR_BUYITEM_1,				
	ERROR_BUYITEM_2,				
	ERROR_BUYITEM_3,				
	ERROR_BUYITEM_4,				
	ERROR_BUYITEM_5,		 		
	ERROR_BUYITEM_6,		 		
	ERROR_BUYITEM_7,		 		
};

enum
{
	ERROR_BUYSKILL_NONE		= 0,	
	ERROR_BUYSKILL_1,				
	ERROR_BUYSKILL_2,				
	ERROR_BUYSKILL_3,				
	ERROR_BUYSKILL_4,				
	ERROR_BUYSKILL_5,				
};

enum
{
	ERROR_SELLITEM_NONE		= 0,	
	ERROR_SELLITEM_1,				
	ERROR_SELLITEM_2,				
	ERROR_SELLITEM_3,				

};

enum
{
	ERROR_REPAIRITEM_NONE		= 0,	
	ERROR_REPAIRITEM_1,					
	ERROR_REPAIRITEM_2,					
	ERROR_REPAIRITEM_3,					
	ERROR_REPAIRITEM_4,					
};


enum
{
	ERROR_DROPITEM_NONE = 0,
	ERROR_DROPITEM_1,			
	ERROR_DROPITEM_2,			
	ERROR_DROPITEM_3,			
	ERROR_DROPITEM_4,			
	ERROR_DROPITEM_5,			
};

enum
{
	ERROR_PICKUPITEM_NONE = 0,	
	ERROR_PICKUPITEM_1,			
	ERROR_PICKUPITEM_2,			
	ERROR_PICKUPITEM_3,			
	ERROR_PICKUPITEM_4,			
	ERROR_PICKUPITEM_5,			
	ERROR_PICKUPITEM_6,			
	ERROR_PICKUPITEM_7,			
	ERROR_PICKUPITEM_8,			
};

enum
{
	ERROR_DESTROYITEM_NONE = 0,
	ERROR_DESTROYITEM_1,			
	ERROR_DESTROYITEM_2,			
	ERROR_DESTROYITEM_3,			
	
	ERROR_DESTROYITEM_4,			
	ERROR_DESTROYITEM_5,			
	
	
	ERROR_DESTROYITEM_6,			
	ERROR_DESTROYITEM_7,			
	ERROR_DESTROYITEM_8,			
	ERROR_DESTROYITEM_9,			
	ERROR_DESTROYITEM_10,			
	ERROR_DESTROYITEM_11,			
	
};

enum
{
	ERROR_EQUIPITEM_NONE = 0,	
	ERROR_EQUIPITEM_1,			
	ERROR_EQUIPITEM_2,			
	ERROR_EQUIPITEM_3,			
	ERROR_EQUIPITEM_4,			
	ERROR_EQUIPITEM_5,			
	ERROR_EQUIPITEM_6,			
	ERROR_EQUIPITEM_7,			
	ERROR_EQUIPITEM_8,			
};

enum
{
	ERROR_ENTITYMENU_NONE = 0,	
	ERROR_ENTITYMENU_1,			
	ERROR_ENTITYMENU_2,			
	ERROR_ENTITYMENU_3,			
};

enum
{
	ERROR_PCTRADE_NONE = 0,		
	ERROR_PCTRADE_1,			
	ERROR_PCTRADE_2,			
	ERROR_PCTRADE_3,			
	ERROR_PCTRADE_4,			
	ERROR_PCTRADE_5,			
	ERROR_PCTRADE_6,			
	ERROR_PCTRADE_7,			
};

enum
{
	ERROR_PARTY_NONE = 0,		
	ERROR_PARTY_1,				
	ERROR_PARTY_2,				
	ERROR_PARTY_3,				
	ERROR_PARTY_4,				
	ERROR_PARTY_5,				
	ERROR_PARTY_6,				
	ERROR_PARTY_7,				
};

enum
{
	ERROR_SKILL_NONE	=	0,
	ERROR_SKILL_0,				
	ERROR_SKILL_1,				
	ERROR_SKILL_2,				
	ERROR_SKILL_3,				
	ERROR_SKILL_4,				
	ERROR_SKILL_5,				
	ERROR_SKILL_6,				
	ERROR_SKILL_7,				

};

enum
{
	ERROR_CONSUMPTIVE_NONE	=	0,
	ERROR_CONSUMPTIVE_0,					
	ERROR_CONSUMPTIVE_1,

	
	ERROR_CONSUMPTIVE_CHARGE_ONLY_NPC,		

	ERROR_CONSUMPTIVE_EQUIP,				
	ERROR_CONSUMPTIVE_CHARGE_COUNT,			
	ERROR_CONSUMPTIVE_DELETE_CHARGE,		


	
	ERROR_CONSUMPTIVE_NOT_USE_NPC,			
	ERROR_CONSUMPTIVE_NOT_SKILL_ITEM,		
	ERROR_CONSUMPTIVE_NOT_LEVEL,			
	ERROR_CONSUMPTIVE_NOT_HAVE_ITEM,		

	ERROR_CONSUMPTIVE_NULL_TARGET_PLAYER,	
	ERROR_CONSUMPTIVE_ALIVE_TARGET_PLAYER,	
	ERROR_CONSUMPTIVE_ONLY_USE_SELF,		
	ERROR_CONSUMPTIVE_ONLY_USE_OTHER,		
	ERROR_CONSUMPTIVE_ONLY_USE_PC,			
};

enum
{
	ERROR_SAVEPORTALPOSITION_NONE	=	0,
	ERROR_SAVEPORTALPOSITION_0,				
};

enum
{
	ERROR_DEPOT_NONE		=	0,
	ERROR_DEPOT_1,							
	ERROR_DEPOT_2,							
	ERROR_DEPOT_3,							
	ERROR_DEPOT_4,							
};

enum
{
	ERROR_ITEMSYSTEM_NONE		=	0,
	ERROR_ITEMSYSTEM_0,						
	ERROR_ITEMSYSTEM_1,						
	ERROR_ITEMSYSTEM_2,						
	ERROR_ITEMSYSTEM_3,						
	ERROR_ITEMSYSTEM_4,						
	ERROR_ITEMSYSTEM_5,						
	ERROR_ITEMSYSTEM_6,						
	ERROR_ITEMSYSTEM_7,						
	ERROR_ITEMSYSTEM_8,						
	ERROR_ITEMSYSTEM_9,						
	ERROR_ITEMSYSTEM_10,					
	ERROR_ITEMSYSTEM_11,					
	ERROR_ITEMSYSTEM_12,					
	ERROR_ITEMSYSTEM_13,					
	ERROR_ITEMSYSTEM_14,					
	ERROR_ITEMSYSTEM_15,					
	ERROR_ITEMSYSTEM_16,					
	ERROR_ITEMSYSTEM_17,					
	
	ERROR_ITEMSYSTEM_18,					
	ERROR_ITEMSYSTEM_19,					
	ERROR_ITEMSYSTEM_20,					
	
	ERROR_ITEMSYSTEM_21,					
	ERROR_ITEMSYSTEM_22,                    
	ERROR_ITEMSYSTEM_23,					

	
	ERROR_ITEMSYSTEM_24,					
	
	
	ERROR_ITEMSYSTEM_25,					
	ERROR_ITEMSYSTEM_26,					
};