

#define GAME_PROTOCOL_VERSION	"GTH_GPV_20030410"



#define CC_CONNECT_MASTERSERVER				0x01
#define CC_DISCONNECT_MASTERSERVER			0x02
#define CC_REQUEST_LOGIN					0x03
#define CC_REQUEST_NOTICE					0x04
#define CC_REQUEST_SERVERGROUP				0x05
#define CC_REQUEST_GAMEDATA					0x06
#define CC_REQUEST_GAMESERVERADDR			0x07

#define CC_REQUEST_READYCREATE				0x08
#define CC_REQUEST_CREATECHARACTER			0x09
#define CC_REQUEST_DELETECHARACTER			0x0a
#define CC_REQUEST_CHECKCHARNAME			0x0b
 


#define CC_CONNECT_GAMESERVER				0x10							
#define CC_DISCONNECT_GAMESERVER			0x11
#define CC_READYTOPLAY						0x12
#define CC_SYNCMESSAGE						0x13
#define CC_CHATMESSAGE						0x14
#define CC_CHATMESSAGE_WHISPER				0x15
#define CC_CHATMESSAGE_PARTY				0x16
#define CC_CHATMESSAGE_DAN					0x17
#define CC_TRANSPORTWORLD					0x18
#define CC_CALLGAMEMASTER					0x19
#define CC_REQUESTSUMMONS					0x1a
#define CC_REPLYSUMMONS						0x1b
#define CC_UPDATEPOSITION					0x1c
#define CC_EVENT_IDLE						0x1d	
#define CC_EVENT_WALK						0x1e	
#define CC_EVENT_WALKLEFT					0x1f	

#define CC_EVENT_WALKRIGHT					0x20	
#define CC_EVENT_BACK						0x21	
#define CC_EVENT_BACKLEFT					0x22	
#define CC_EVENT_BACKRIGHT					0x23	
#define CC_EVENT_RUN						0x24	
#define CC_EVENT_RUNLEFT					0x25	
#define CC_EVENT_RUNRIGHT					0x26	
#define CC_EVENT_TURNLEFT					0x27	
#define CC_EVENT_TURNRIGHT					0x28	
#define CC_EVENT_MOVELEFT					0x29	
#define CC_EVENT_MOVERIGHT					0x2a	
#define CC_EVENT_ATTACK						0x2b	
#define CC_EVENT_RESPAWN					0x2c	
#define CC_EVENT_MOUSEWALK					0x2d	
#define CC_EVENT_MOUSERUN					0x2e	
#define CC_EVENT_SIT						0x2f

#define CC_EVENT_STAND						0x30	
#define CC_EVENT_SKILL						0x31	
#define CC_DROPITEM							0x32
#define CC_PICKUPITEM						0x33
#define CC_REQUEST_GETINVENTORYITEM			0x34
#define CC_REQUEST_GETEQUIPITEM				0x35

#define CC_REQUEST_NPCCHAT					0x37
#define CC_REQUEST_QUITNPCCHAT				0x38
#define CC_REQUEST_NPCSELECTMESSAGE			0x39
#define CC_REQUEST_WEAPONCHANGE				0x3a
#define CC_REQUEST_GENCHANGE				0x3b
#define	CC_REQUEST_STATUSUP					0x3c
#define	CC_REQUEST_STORE					0x3d
#define CC_REQUEST_BUYITEM					0x3e
#define CC_REQUEST_SELLITEM					0x3f

#define CC_REQUEST_CHEATCODE				0x40
#define	CC_REQUEST_BINDING					0x41
#define	CC_REQUEST_EPACKSTORE				0x42
#define	CC_REQUEST_EPACKUSE					0x43
#define CC_REQUEST_REPAIR					0x44
#define CC_REQUEST_DESTROY_ITEM				0x45
#define CC_REQUEST_PCTRADE					0x46
#define CC_REQUEST_PARTY					0x47

#define CC_REQUEST_SKILLLEVELUP				0x49
#define CC_REQUEST_ADDSKILL					0x4a
#define CC_REQUEST_PCINFO					0x4b
#define CC_HOTKEY							0x4c

#define CC_REQUEST_DELETE_QUESTSTATUS		0x4d					

#define CC_REQUEST_LEARN_SKILL				0x4f
#define CC_REQUEST_USE_PORTAL				0x50
#define CC_REQUEST_SAVE_PORTAL_POSITION		0x51					
#define CC_REQUEST_BUY_SKILL				0x52
#define CC_REQUEST_ITEMSYSTEM				0x53					
#define CC_QUESTLOGIC						0x54
#define CC_FRIENDS							0x55					

#define CC_GUILD							0x57					
#define CC_BEFORE_TELEPORT					0x58
#define	CC_TELEPORT							0x59
#define CC_REQUEST_USE_POTION				0x5a					
#define CC_REQUEST_DELETE_AUTOEFFECT		0x5b					


#define CC_REQUEST_USE_MASIC_BOOK			0x5c	






#define GSC_SERVERGROUPINFO					0x70
#define GSC_DROPSERVERGROUP					0x71

#define GSC_MEMBERSERVERINFO				0x72
#define GSC_MYSERVERINFO					0x73
#define GSC_DROPMYSERVER					0x74

#define GSC_REQUEST_OTHERSERVER				0x75
#define GSC_REPLY_OTHERSERVER				0x76





#define GSC_CONNECTREP						0x80
#define GSC_SYNCMESSAGE						0x81	
#define GSC_CHATMESSAGE						0x82
#define GSC_CHATMESSAGE_WHISPER				0x83
#define GSC_CHATMESSAGE_PARTY				0x84
#define GSC_CHATMESSAGE_DAN					0x85
#define GSC_TRANSPORTWORLDREP				0x86
#define GSC_CHANGESERVER					0x87
#define GSC_CHANGEWORLD						0x88
#define GSC_SETSHUTDOWNTIMER				0x89
#define GSC_NOTICEMESSAGE					0x8a
#define GSC_CALLGAMEMASTER					0x8b
#define GSC_REQUESTSUMMONS					0x8c
#define GSC_REPLYSUMMONS					0x8d
#define GSC_EVENT_IDLE						0x8e	
#define GSC_EVENT_WALK						0x8f
	
#define GSC_EVENT_WALKLEFT					0x90	
#define GSC_EVENT_WALKRIGHT					0x91	
#define GSC_EVENT_BACK						0x92	
#define GSC_EVENT_BACKLEFT					0x93	
#define GSC_EVENT_BACKRIGHT					0x94	
#define GSC_EVENT_RUN						0x95	
#define GSC_EVENT_RUNLEFT					0x96	
#define GSC_EVENT_RUNRIGHT					0x97	
#define GSC_EVENT_TURNLEFT					0x98	
#define GSC_EVENT_TURNRIGHT					0x99	
#define GSC_EVENT_MOVELEFT					0x9a	
#define GSC_EVENT_MOVERIGHT					0x9b	
#define GSC_EVENT_ATTACK					0x9c	
#define GSC_EVENT_DAMAGE					0x9d	
#define GSC_EVENT_DIE						0x9e	
#define GSC_EVENT_RESPAWN					0x9f
	
#define GSC_EVENT_MOUSEWALK					0xa0	
#define GSC_EVENT_MOUSERUN					0xa1
#define GSC_EVENT_SIT						0xa2
#define GSC_EVENT_STAND						0xa3
#define GSC_EVENT_SKILL						0xa4
#define GSC_ADDITEMOBJECT					0xa5
#define GSC_SYNCITEMOBJECT					0xa6
#define GSC_DELETEITEMOBJECT				0xa7
#define GSC_REPLY_GETINVENTORYITEM			0xa8
#define GSC_REPLY_GETEQUIPITEM				0xa9
#define GSC_REPLY_DROPITEM					0xaa
#define GSC_REPLY_PICKUPITEM				0xab
#define GSC_ADDMULTIITEMOBJECT				0xac
#define GSC_LOOTVALUE						0xad
#define GSC_NPCINFO							0xae
#define GSC_REPLY_NPCCHAT					0xaf
#define GSC_REPLY_QUITNPCCHAT				0xb0
#define GSC_NPCMESSAGE						0xb1
#define GSC_REPLY_WEAPONCHANGE				0xb2
#define GSC_LEVELUP							0xb3
#define GSC_REPLY_GENCHANGE					0xb4
#define GSC_REPLY_STATUSUP					0xb5
#define GSC_REPLY_STORE						0xb6
#define GSC_REPLY_BUYITEM					0xb7
#define GSC_REPLY_SELLITEM					0xb8
#define	GSC_REPLY_BINDING					0xb9
#define	GSC_REPLY_EPACKSTORE				0xba
#define	GSC_AUTORECOVERY					0xbb
#define	GSC_REPLY_EPACKUSE					0xbc
#define GSC_REPLY_REPAIR					0xbd
#define GSC_REPLY_DESTROY_ITEM				0xbe
#define GSC_REPLY_PCTRADE					0xbf

#define GSC_SERVERACKMSG					0xc0
#define GSC_NOTFOUNDPC						0xc1

#define GSC_REPLY_PARTY						0xc2
#define GSC_REQUEST_PARTYINFO				0xc3
#define GSC_REPLY_PARTYINFO					0xc4

#define GSC_ADDITEMINV						0xc5							
#define GSC_DELETEITEMINV					0xc6							
#define GSC_QUESTSTATUS_INFO				0xc7							

#define GSC_REJECT_CLIENT					0xc8	
#define GSC_REPLY_CHEATCODE					0xc9
#define GSC_REPLY_SKILLLEVELUP				0xca
#define GSC_REPLY_ADDSKILL					0xcb
#define GSC_EVENT_SKILLCASTING				0xcc
#define GSC_AFFECT							0xcd
#define GSC_REPLY_PCINFO					0xcf

#define GSC_QUEST_STEP						0xd0					

#define GSC_REPLY_LEARN_SKILL				0xd1
#define GSC_REPLY_USE_PORTAL				0xd2
#define GSC_REPLY_SAVE_PORTAL_POSITION		0xd3					

#define GSC_QUEST_ITEM_INFO					0xd4
#define GSC_REPLY_BUY_SKILL					0xd5

#define GSC_QUESTLOGIC						0xd6

#define GSC_REPLY_ITEMSYSTEM				0xd7
#define GSC_REPLY_FRIENDS					0xd8					

#define GSC_EVENT_MONSTER_SKILL				0xd9
#define GSC_EVENT_MONSTER_SKILLCASTING		0xda

#define GSC_GUILD_REPLY						0xdb					
#define GSC_GUILD_REQUEST					0xdc					

#define GSC_EVENT_BEFORE_TELEPORT			0xdd
#define GSC_EVENT_TELEPORT					0xde
#define GSC_REPLY_USE_POTION				0xdf					
#define	GSC_AUTOQUESTSTATUS_INFO            0xef                    
#define GSC_ANSWER_AUTOEFFECT		        0xff					




#define MSC_ACCEPTCLIENT					0xe0
#define MSC_PATCHSERVERADDR					0xe1
#define MSC_NOTICEINFO						0xe2	
#define MSC_REPLYLOGIN						0xe3	
#define MSC_SERVERGROUPINFO					0xe4
#define MSC_GAMEDATA						0xe5
#define MSC_GAMESERVERADDR					0xe6
#define MSC_REPLY_READYCREATE				0xe7
#define MSC_REPLY_CREATECHARACTER			0xe8
#define MSC_REPLY_DELETECHARACTER			0xe9
#define MSC_REPLY_CHECKCHARNAME				0xea
#define MSC_REJECTCLIENT					0xeb



#define GSC_CHATTINGMSG						0xec




#define CC_SYSTEMADMIN						0xf0
#define GSC_SYSTEMADMIN						0xf1

#define GC_RELIABLE_PING					0xf2
#define GC_UNRELIABLE_PING					0xf3

#define CC_MONITOR							0xf4
#define MSC_MONITOR							0xf5

#define CC_CSAUTH							0xf6
#define GSC_CSAUTH							0xf7


#define CC_EXTEND							0xf8
#define GSC_EXTEND							0xf9


#define EXTEND_SECOND						0xfa











#define CC_SUB_EVENT_SOCIAL_SHOUT			0x01
#define CC_SUB_EVENT_SOCIAL_BOW				0x02


#define CC_MAILSYSTEM						0x03			

#define CC_WORLDCHATTING					0x04			

#define CC_SAVE_SKIN_PART					0x05			


#define GSC_SUB_EVENT_SOCIAL_SHOUT			0x51
#define GSC_SUB_EVENT_SOCIAL_BOW			0x52
#define GSC_SUB_EVENT_COMPLETE_EFFECT		0x53


#define GSC_MAILSYSTEM						0x54			
#define GSC_MAIL_REQUEST					0x55
#define GSC_MAIL_REPLY						0x56


#define GSC_WORLDCHATTING					0x57			
#define GSC_WORLDCHATTING_REQUEST			0x58			
#define GSC_WORLDCHATTING_REPLY				0x59			

																						
#define CC_DAN_BATTLE						0x60			
#define GSC_DAN_BATTLE						0x61			
#define GSM_DAN_BATTLE						0x63			
#define GMS_DAN_BATTLE						0x64			



#define CC_REQUEST_CHATBAN_FLAG				0x65			
#define CC_REQUEST_CHATBAN_START			0x66			
#define CC_REQUEST_CHATBAN_CANCEL			0x67			
#define CC_REQUEST_CHATBAN_GMCANCEL			0x68			

#define GSC_ANSWER_CHATBAN_FLAG				0x69            


#define GSC_EXTEND_SEND_USE_MASIC_BOOK		0x70
#define GSC_EXTEND_REPLY_USE_MASIC_BOOK		0x71











#define CC_REQUEST_CHAOVALUE				0x0006			
#define GSC_ANSWER_CHAOVALUE				0x0007			
#define GSC_SEND_ADDCHAOSINFO				0x0008          
#define GSC_SEND_DECCHAOSINFO				0x0009			




#define CC_REQUEST_GONRYUNBATTLEPRACTICE    0x0010          
#define GSC_ANSWER_GONRYUNBATTLEPRACTICE    0x0011			

#define GSC_BILLING							0x6A			


#define CC_GB_BATTLE						0x6b            
#define GSC_GB_BATTLE						0x6c            



#define CC_RELOAD_LOGIC						0x6e			


#define CC_MAILBOX							0x72
#define GSC_MAILBOX							0x73



#define	CC_REQUEST_USE_EPACK_CHARG_SOUL		0x74
#define	GSC_REPLY_USE_EPACK_CHARG_SOUL		0x75


#define GSC_EXTEND_EVENT_SKILL_ERROR		0x76


#define	CC_REQUEST_CHRISTMAS_EVENT			0x77
#define	GSC_REPLY_CHRISTMAS_EVENT			0x78


#define CC_EXTEND_WORLDCHATTING_COUNT		0x79 


#define CC_POSTSYSTEM						0x7a
#define GSC_POSTSYSTEM						0x7b			


#define GSC_WORLDCHATTING_COUNT				0x7c


#define CC_WORLD_CHANGE						0x7d
#define GSC_WORLD_CHANGE					0x7e













enum enumExtendSecondPacket
{
	WEATHER_SYSTEM		= 0x0001,	
	ITEM_REPAIR			= 0X0002,	
	HELPER_SYSTEM		= 0x0003,	
	GIFTCARD			= 0x0004,	
	TERRA		    	= 0x0005,	
	EXP_EVENT			= 0x0006,	
	GMsystem			= 0x0007,   
	CASH_MALL_ITEM		= 0x0008,	
	GAMBLE_SYSTEM		= 0x0009,	
	ITEM_EXTEND_SYSTEM	= 0x000A,	
	SC_DISCONNECT		= 0x000B,   
	ITEM_SUMMON_SYSTEM	= 0x000C,	
	GS_TO_GMS_PACKET	= 0x000D,	
	GMS_TO_GS_PACKET	= 0x000E,
	GS_TO_GS_PACKET		= 0x000F,
	AHNLAB				= 0x0010,	
	AHNLAB_ERROR		= 0x0011,	
	NEW_DANBATTLE		= 0x0012,	
	CHAO_POINT_EVENT	= 0X0013,   

};


struct tagExtendSecondPacket_GMsystem{
	enum{
		GMsystem_ChatBan=0,
		GMsystem_PKtime=1,
		GMsystem_NProtect=2,
	};

	struct tagNProtect{
		enum{
			cs_request_AUTH=0,
			sc_response_AUTH,
			cs_request_AUTH_dll_change,
			sc_response_AUTH_dll_change,

			cs_request_AUTHstate,
			sc_response_AUTHstate,

			gsms_request_change,
			msgs_notify_change,
		};
	};


	struct tagNotify{
		enum{
			sc_disconnet=0,
		};
	};

	struct tagPKtime{
		enum{
			cs_request_change=0,
			sc_notify_change=1,
			gsms_request_change=2,
			msgs_notify_change=3,
			cs_request_status=4,
			sc_response_status=5,
		};

	};

	struct tagChatBan{
		enum{			
			sc_chat_allow=0,
			sc_chat_block=1,
			cs_request_chat_block,
			sc_response_chat_block,

			cs_request_chat_allow,
			sc_response_chat_allow,

			cs_chat_request_reamin_block_time,
			sc_chat_response_reamin_blick_time,
		};
	};
};





enum enumExtendSecondPacket_WeatherSystem{
	CC_WEATHER_SYSTEM   = 0x0001,
	GSC_WEATHER_SYSTEM  = 0x0002,
};


enum enumExtendSecondPacket_ItemRepare{
	CC_ITEM_REPAIR		= 0x0001,
	GSC_ITEM_REPAIR		= 0x0002,
};



enum
{
	GSC_CHANGE_PVPMODE,					
};



enum
{
	SYSTEMADMIN_SERVERSHUTDOWN		=	0,
	SYSTEMADMIN_SETSHUTDOWNTIMER,
	SYSTEMSDMIN_GOTOPLAYER,
	SYSTEMSDMIN_NOTICE,
	SYSTEMADMIN_SETNOTICEINFO,
	SYSTEMADMIN_REQUESTFINDPC,
	SYSTEMADMIN_REPLYFINDPC,
	SYSTEMSDMIN_GOTOMONSTER,
	SYSTEMSDMIN_GMBUSYONOFF,
	SYSTEMSDMIN_GMHIDEONOFF,
	SYSTEMSDMIN_REQUESTSUMMONMONSTER,
	SYSTEMADMIN_REPLYSUMMONMONSTER,
};



enum
{
	PCTRADE_REQUEST		=	0,		
	PCTRADE_ADMIT,					
	PCTRADE_REJECT,					
	PCTRADE_OK,						
	PCTRADE_CANCEL,					
	PCTRADE_CONFIRM,				
	PCTRADE_EXIT,					
	PCTRADE_ITEM,					
	PCTRADE_SE,						
};



enum
{
	
	PARTY_REQUEST_ORGANIZE		=	0,		
	PARTY_ADMIT_ORGANIZE,					
	PARTY_REJECT_ORGANIZE,					
	PARTY_REQUEST_JOIN,						
	PARTY_ADMIT_JOIN,						
	PARTY_REJECT_JOIN,						
	
	PARTY_OUT,						
	PARTY_FORCEDOUT,				
	PARTY_DISORGANIZE,				

	
	PARTY_CANJOIN,					
	PARTY_ITEMDIVIDETYPE,			

	PARTY_SENDALL,					
	PARTY_UPDATE,					
	PARTY_HOLDING,					

	PARTY_CHATMESSAGE,				

	PARTY_ERROR,					
};



enum
{
	FRIENDS_INVITE = 0,			
	FRIENDS_ACCEPT,				
	FRIENDS_REJECT,				
	FRIENDS_REMOVE,				
	FRIENDS_LIST,				
	FRIENDS_ADD,				
	FRIENDS_CHANGE,				

	FRIENDS_ERROR_BUSY,			
	FRIENDS_ERROR_NOT_READY,	
	FRIENDS_ERROR_WRONG_USER,	
};



enum
{
	PCINFO_NONE					=	0,
	PCINFO_BASIC,
};




enum
{
	CHEATCODE_GETEXP				=	0,
	CHEATCODE_GETGENEXP,
	CHEATCODE_SKILLPOINT,
	CHEATCODE_GETSKILL,
	CHEATCODE_GETMAXSE,
	CHEATCODE_CLEARQUEST,
	CHEATCODE_ADDITEM,
	CHEATCODE_GETGENCAPABILITY,
	CHEATCODE_MAXRASA,
	CHEATCODE_AWAKEN,
	CHEATCODE_READYAWAKEN,
	CHEATCODE_GOMONSTER,
	
	
	CHEATCODE_ITEM,
	CHEATCODE_MONSTER,
	
	CHEATCODE_ATKDELAY,
	
	CHEATCODE_LEVEL,
	CHEATCODE_SKILL,
	CHEATCODE_INITSKILL,
	
	CHEATCODE_ITEMDROPTEST,	
	
	CHEATCODE_MONSTERSPAWN,
	
	CHEATCODE_MONSTERKILL,	
	CHEATCODE_ADDQUESTITEM,
	
	CHEATCODE_OUTPUTGUILDINFO,
	
	CHEATCODE_GET_MEMBERSHIP_TYPE,

	
	CHEATCODE_FORCEQUIT_BY_GM,

	
	CHEATCODE_HIDENAME,
	
	CHEATCODE_CLEARINVEN,
	
	
	CHEATCODE_KILLME,

	
	CHEATCODE_DANBATTLE_PCPOINT,
	
	
};





enum
{
	QUESTLOGIC_CHATMSG				=	0,
	QUESTLOGIC_AWAKEN,
	
	QUESTLOGIC_INITSTATUS,
};





enum
{
	DEPOT_OPEN				=	0,
	DEPOT_GETITEM,
	DEPOT_ITEM,
	DEPOT_NAK,

	
	
	PRECOCITY_OPEN,
	PRECOCITY_ITEM,			
	PRECOCITY_COMPLETE,

	
	
	CRAFT_OPEN,				
	CRAFT_CLOSE,
	CRAFT_ITEM,				
	CRAFT_PREPARE,			
	CRAFT_COMPLETE,			

	
	EVENT_CRAFT_OPEN,				
	EVENT_CRAFT_CLOSE,
	EVENT_CRAFT_ITEM,				
	EVENT_CRAFT_PREPARE,			
	EVENT_CRAFT_COMPLETE,			
	EVENT_CRAFT_LOADEVENT,			
	
	
	
	
	BOOTH_SELL_OPEN,		
	BOOTH_SELL_ITEM,		
	BOOTH_SELL_START,		
	BOOTH_SELL_CLOSE,		

	BOOTH_BUY_OPEN,			
	BOOTH_BUY_ITEM,			
	BOOTH_BUY_CLOSE,		
	BOOTH_BUY_UPDATE,		

	
	
	UPGRADE_OPEN,			
	UPGRADE_CLOSE,			
	UPGRADE_ITEM,			
	UPGRADE_PREPARE,		
	UPGRADE_COMPLETE,		
	
	DELETE_PREPARE,			
	DELETE_COMPLETE,		

	
	QUESTSCROLL_OBTAINOPEN,
	QUESTSCROLL_OBTAINPREPARE,
	QUESTSCROLL_OBTAINCOMPLETE,
	QUESTSCROLL_OBTAINCLOSE,
	QUESTSCROLL_COMPLETE,
	QUESTSCROLL_COMBOLISTCHANGE,
	
	AUTOQUESTSCROLL_OBTAINOPEN,
	AUTOQUESTSCROLL_COMPLETE,
	AUTOQUESTSCROL_ERROR,
	
	AUTOQUESTSCROLL_START,			
    AUTOQUESTEFFECT_COMPLETE,		
	AUTOQUESSCROLL_FAIL,			
	AUTOQUESTSCROLL_END,			
	
	AUTOQUESTSCROLL_NPCINVENTORYOPEN,
	AUTOQUESTSCROLL_NPCINVENTORYCLOSE,
	AUTOQUESTSCROLL_NPCINVENTORYITEM,
	AUTOQUESTSCROLL_NPCINVENTORYPREPARE,

	

	EXCHANGE_CLOSE,
	EXCHANGE_ITEM,				
	EXCHANGE_PREPARE,			

	

};





enum
{
	PCLIST_ADD				=	0,
	PCLIST_DELETE,
	PCLIST_UPDATE,
	PCLIST_REQUEST,
	PCLIST_LIST,
	PCLIST_FRIENDS_LIST,
	PCLIST_FRIENDS_UPDATE,
};






enum
{
	
	GUILD_ORGANIZE		=	0,		
	GUILD_ORGANIZE_REQUEST,			
	GUILD_DISORGANIZE,				

	GUILD_AUTHORITY,				

	GUILD_INVITE_REQUEST,			
	GUILD_INVITE_REPLY,				
	GUILD_INVITE_CANCEL,			

	GUILD_SECEDE,					
	GUILD_BANISH,					

	GUILD_CONNECT,					

	
	GUILD_SENDALL,					
	GUILD_UPDATE,					
	GUILD_HOLDING,					

	GUILD_CHATMESSAGE,				

	GUILD_CHANGEMASTER,				
	GUILD_ADDSUBMASTER,				
	GUILD_REMOVESUBMASTER,			
	GUILD_ADDFACTIONMASTER,			
	GUILD_REMOVEFACTIONMASTER,		
	GUILD_DELETE_MASTER,			

	GUILD_GUILDMARK,				
	GUILD_GUILDMARKINFO,			

	GUILD_SUBSCRIBE,				
	GUILD_SUBSCRIBE_REQUEST,		
	GUILD_SCHEDULE,

	GUILD_ERROR,					
	GUILD_SYNC,						

};




enum
{
	MAIL_STATE				=	0,
	MAIL_SEND,
	MAIL_RECEIVE,
	MAIL_DELETE,
	MAIL_VIEW,
	MAIL_SAVE,
	MAIL_ARRIVE,			
};

enum																					
{

	DANB_REQUEST_BATTLE			= 0,
	DANB_REQUEST_CANCEL,
	DANB_SUGGEST_BATTLE,
	DANB_SUGGEST_RESULT,
	DANB_SETSTATUS,								
	DANB_REQUESTER_LIST,
	DANB_MESSAGE,
	DANB_CHANGE_BATTLEMAP,
	DANB_BATTLE_READY,							
	DANB_BATTLE_START,	
	DANB_BATTLE_INFO,
	DANB_BATTLE_RESULT,
	DANB_INIT_CHAO,								
	DANB_BATTLE_DAN,				
	DANB_BATTLE_REWARD,
	DANB_BATTLE_REFRESH_PERSONDATA,				
	DANB_BATTLE_TEST_MODE,						
	DANB_ERROR,	
};



enum
{
	BATTLE_PRACTICE_GET_MYINFO				=0,			
	BATTLE_PRACTICE_GET_OTHERLISTINFO		=1,			
	BATTLE_PRACTICE_SEND_OTHERMYINFO		=2,			
	BATTEL_PRACTICE_GET_CANCEL				=3,			
	BATTLE_PRACTICE_SEND_CANCEL				=4,			
	BATTLE_PRACTICE_END						=5,			
	BATTLE_PRACTICE_REQUEST_DELETE_USER		=6,			
	BATTEL_PRACTICE_REQUEST_BATTELBATTING	=7,			
	BATTLE_PRACTICE_REQUEST_BATTELGENERATE	=8,			
	BATTLE_PRACTICE_BATTING_RESULT			=9,			
	BATTLE_PRACTICE_GENERATE_RESULT			=10,		
	BATTLE_PRACTICE_BATTINGTRADE_REQUEST			=11,		
	BATTLE_PRACTICE_BATTINGTRADE_RESULT			=12,		
	BATTLE_PRACTICE_BATTINGTRADE_REJECT			=13,		
	BATTLE_PRACTICE_BATTINGTRADE_OK				=14,		
	BATTLE_PRACTICE_BATTINGTRADE_CANCEL			=15,		
	BATTLE_PRACTICE_BATTINGTRADE_CONFIRM			=16,		
	BATTLE_PRACTICE_BATTINGTRADE_EXIT			=17,		
	BATTLE_PRACTICE_BATTINGTRADE_ITEM			=18,		
	BATTLE_PRACTICE_BATTINGTRADE_SE				=19,		
	BATTLE_PRACTICE_STATE					=20,		
	BATTLE_PRACTICE_RWORDFIELD				=21,		
	BATTLE_PRACTICE_EFFECT_MODE				=22,		
	BATTEL_PRACTICE_INFO					=23,		
	BATTLE_PRACTICE_CHEATBATTLEIN			=24,
	BATTLE_PRACTICE_CHEATBATTLEOUT			=25,


	BATTLE_PRACTICE_FIELDOUT				=26,
	BATTLE_PRACTICE_BATTING_REJECT			=27,
	BATTLE_PRACTICE_GENERATE_REJECT			=28,
	BATTLE_PRACTICE_BAN						=29,
	BATTLE_PRACTICE_START					=30,
	BATTLE_PRACTICE_POSITION				=31,
	BATTLE_PRACTICE_MSG						=32,										
	BATTEL_PRACTICE_RESULT					=33,		
	BATTEL_PRACTICE_NAKE_RESULT				=34,		
	BATTEL_PRACTICE_ITEM_RESULT				=35,		
	BATTEL_PRACTICE_MYINFO_TOUSER			=36,		
	BATTEL_PRACTICE_DELETE_USER				=37,
	BATTLE_PRACTICE_BAN_BATTING				=38,
	BATTLE_PRACTICE_CANCEL_BATTING			=39,
	BATTLE_PRACTICE_FAILADDITEM				=40,
	BATTLE_PRACTICE_OPEN					=41,
};




enum
{
	POSTSYSTEM_OPEN		= 0,
	POSTSYSTEM_EXIT_WIN,
	POSTSYSTEM_SEND,	
	POSTSYSTEM_DELETE,		
	POSTSYSTEM_STATE,
	POSTSYSTEM_WRITEOPEN,
	POSTSYSTEM_SENDCOMPLETE,
	POSTSYSTEM_DELETENAK,
	POSTSYSTEM_NOTIFY,
};


enum
{
	MAILBOX_OPEN		= 0,
	MAILBOX_OK,
	MAILBOX_CANCEL,	
	MAILBOX_RECEIVE_ITEMS,
	MAILBOX_EXIT,
	MAILBOX_ITEM,
	MAILBOX_SE,
	MAILBOX_UNDOINVENITEM,
};
